#!/usr/bin/env node
// Fetches tenant slugs from Supabase at build time and writes them to
// lib/tenants.generated.ts so generateStaticParams() can pre-render
// each tenant's pages.
//
// Falls back to ['demo'] if Supabase env vars are missing or the request
// fails — the build should never break just because a config fetch
// hiccuped, and 'demo' always exists from the migration.

import { writeFile, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const outFile = join(repoRoot, "lib", "tenants.generated.ts");

// Load .env.local manually so this works outside of Next's runtime (e.g. via
// `node scripts/...`). CI passes envs directly so this is a no-op there.
for (const filename of [".env.local", ".env"]) {
  const path = join(repoRoot, filename);
  if (!existsSync(path)) continue;
  const text = await readFile(path, "utf8");
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    const [, key, raw] = m;
    if (process.env[key]) continue;
    let value = raw.trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    process.env[key] = value;
  }
}

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

const FALLBACK = ["demo"];

async function fetchSlugs() {
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    console.warn(
      "[prebuild-tenants] NEXT_PUBLIC_SUPABASE_* env vars missing — using fallback",
    );
    return FALLBACK;
  }

  const url = `${SUPABASE_URL}/rest/v1/tenants?select=slug&order=slug.asc`;
  try {
    const res = await fetch(url, {
      headers: {
        apikey: SUPABASE_KEY,
        Authorization: `Bearer ${SUPABASE_KEY}`,
      },
    });
    if (!res.ok) {
      console.warn(
        `[prebuild-tenants] Supabase responded ${res.status} ${res.statusText} — using fallback`,
      );
      return FALLBACK;
    }
    const rows = await res.json();
    const slugs = rows
      .map((r) => r.slug)
      .filter((s) => typeof s === "string" && /^[a-z0-9][a-z0-9-]{0,62}$/.test(s));
    if (slugs.length === 0) {
      console.warn("[prebuild-tenants] No tenants returned — using fallback");
      return FALLBACK;
    }
    return slugs;
  } catch (err) {
    console.warn(`[prebuild-tenants] Fetch failed: ${err.message} — using fallback`);
    return FALLBACK;
  }
}

const slugs = await fetchSlugs();
const generated = `// AUTO-GENERATED by scripts/prebuild-tenants.mjs at build time.
// Do not edit by hand — re-run the build to refresh.

export const tenantSlugs: readonly string[] = ${JSON.stringify(slugs, null, 2)} as const;
`;

await writeFile(outFile, generated, "utf8");
console.log(
  `[prebuild-tenants] Wrote ${slugs.length} tenant slug(s) to lib/tenants.generated.ts: ${slugs.join(", ")}`,
);
